# Generated by Django 4.0.5 on 2022-06-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_asd_familia_hermana_papa_delete_curso_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hermana',
        ),
        migrations.DeleteModel(
            name='Mama',
        ),
        migrations.DeleteModel(
            name='Papa',
        ),
        migrations.AlterField(
            model_name='familia',
            name='relacion',
            field=models.CharField(max_length=80),
        ),
    ]
